
[timeout]
flip = 5
wait_for_request = 60

[webdriver]
path = "PATH_TO_CHROME_DRIVER_BINARY"

[provider]
path = "PATH_TO_PROVIDER_DIRECTORY"
providers = [
    "copymanga",
    "dmzj",
    "manhuagui",
    "wenku8",
]

[output]
directory = "output"